services:
    it-tools:
        image: 'corentinth/it-tools:latest'
        container_name: it-tools
        ports:
            - '9080:80'
        restart: unless-stopped
        networks:
            - traefik-proxy
        labels:
          traefik.enable: true
          traefik.http.routers.it-tools.rule: Host(`it-tools.docker.gta.bar`)
          traefik.http.routers.it-tools.entrypoints: websecure
          traefik.http.routers.it-tools.tls.certresolver: myresolver

networks:
  traefik-proxy:
    driver: bridge
    external: true

