services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - /mnt/macos:/storage
    restart: always
    stop_grace_period: 2m
